module.exports = {
  apps: [
    {
      name: "punto-cambio-server",
      script: "./dist/index.js",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        DATABASE_URL:
          "postgresql://postgres:Esh2ew8p@34.66.51.85:5432/punto_cambio",
        DB_USER: "postgres",
        DB_PASSWORD: "Esh2ew8p",
        DB_HOST: "34.66.51.85",
        DB_PORT: "5432",
        DB_NAME: "punto_cambio",
        DB_POOL_MIN: 2,
        DB_POOL_MAX: 10,
        DB_TIMEOUT: 30000,
        JWT_SECRET: "s3rv13ntr3g4_super_secure_jwt_key_change_in_production",
        FRONTEND_URL: "http://34.70.184.11:3001",
        VITE_API_URL: "http://34.70.184.11:3001/api",
        LOG_LEVEL: "info",
        RATE_LIMIT_WINDOW_MS: 900000,
        RATE_LIMIT_MAX_REQUESTS: 100,
        LOGIN_RATE_LIMIT_MAX_REQUESTS: 5,
      },
      error_file: "./logs/error.log",
      out_file: "./logs/combined.log",
      log_file: "./logs/combined.log",
      time: true,
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=1024",
    },
  ],
};
