// Catálogo de fotografías de la guía de reconocimiento: cómo se hace cada prueba,
// resultado bueno, oro de menor ley y resultado malo. Archivos en /public/metal-guide.

type Credit = { titulo: string; autor: string; licencia: string; url: string };
export type GuidePhoto = { src: string; alt: string; caption: string; credit?: Credit };

const TRAINING = { titulo: "Capacitación «Reconocimiento de oro»", autor: "Rashell Silva / Punto Cambio", licencia: "Material interno de capacitación", url: "" };
const cc = (titulo: string, autor: string, licencia: string, url: string): Credit => ({ titulo, autor, licencia, url });
const CATEB = "Mauro Cateb";

export const PHOTOS = {
  // Capacitación
  "acidos": { src: "acidos.jpg", alt: "Soluciones para probar oro 10K, 14K y 18K", caption: "Ácidos 10K, 14K y 18K. Revise la fecha de vencimiento.", credit: TRAINING },
  "piedra": { src: "piedra.jpg", alt: "Piedra para la prueba", caption: "Piedra tipo afilar cuchillo para dejar la marca.", credit: TRAINING },
  "lija": { src: "lija.jpg", alt: "Lija de grano fino", caption: "Lija fina: la marca se hace sobre ella.", credit: TRAINING },
  "limas": { src: "limas.jpg", alt: "Juego de limas", caption: "Juego de limas de aguja.", credit: TRAINING },
  "lupa": { src: "lupa.jpg", alt: "Lupa de joyero 10X", caption: "Lupa 10X para leer el sello.", credit: TRAINING },
  "reaccion-18k": { src: "reaccion-18k.jpg", alt: "Oro 18K con ácido", caption: "18K / 750: la marca sigue dorada, sin mancha.", credit: TRAINING },
  "reaccion-oro-blanco": { src: "reaccion-oro-blanco-rodinado.jpg", alt: "Oro blanco rodinado con ácido", caption: "Oro blanco rodinado: la gota queda clara.", credit: TRAINING },
  "reaccion-14k": { src: "reaccion-14k.jpg", alt: "Oro 14K con ácido", caption: "14K: mancha café oscura.", credit: TRAINING },
  "reaccion-14k-lamina": { src: "reaccion-14k-lamina.jpg", alt: "Lámina de 14K con ácido", caption: "14K: mancha café al aplicar el ácido.", credit: TRAINING },
  "reaccion-10k": { src: "reaccion-10k.jpg", alt: "Oro 10K con ácido", caption: "10K: café que burbujea verde-blanco.", credit: TRAINING },
  "intensidad": { src: "intensidad-reaccion.jpg", alt: "Burbuja, burbujeo y efervescencia", caption: "Burbuja (14K) · Burbujeo (10K) · Efervescencia verde (cobre: no es oro).", credit: TRAINING },
  // Wikimedia Commons / Flickr (licencias abiertas)
  "piedra-toque": { src: "piedra-toque.jpg", alt: "Piedras de toque con marcas de oro", caption: "Marcas doradas uniformes sobre la piedra de toque.", credit: cc("2 Touchstones", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:2_Touchstones.JPG") },
  "piedra-toque-juego": { src: "piedra-toque-juego.jpg", alt: "Juego de piedra de toque y ácidos", caption: "Juego de piedra y ácidos 18K, 14K y 9K.", credit: cc("Pierre de touche", "jcw", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Pierre_de_touche.jpg") },
  "sello-plata-925": { src: "sello-plata-925.jpg", alt: "Sellos 925 en plata", caption: "Plata: «Ag 925» en la pieza y «925» en la placa junto al cierre.", credit: cc("Collier poinçon argent 925", "Chatsam", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Collier_poin%C3%A7on_argent_925.JPG") },
  "oro-blanco-750": { src: "oro-blanco-750.jpg", alt: "Anillo de oro blanco 750", caption: "Oro blanco 750 (18K): color parejo en toda la pieza.", credit: cc("750-white gold ring", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:750-white_gold_ring.jpg") },
  "oro-blanco-rodinado": { src: "oro-blanco-rodinado.jpg", alt: "Oro blanco con baño de rodio", caption: "Oro blanco con baño de rodio (rodinado).", credit: cc("White-gold--rhodium-plated", "Schtone", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:White-gold--rhodium-plated.jpg") },
  "iman-neodimio": { src: "iman-neodimio.jpg", alt: "Imanes de neodimio", caption: "Imanes de neodimio: los pequeños comunes no bastan.", credit: cc("Neodymium magnet 1140510", "Nevit Dilmen", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Neodymium_magnet_1140510.jpg") },
  "anillos-oro": { src: "anillos-oro.jpg", alt: "Aros de oro amarillo", caption: "Oro amarillo macizo: color cálido y parejo, incluso en los bordes gastados.", credit: cc("Gold wedding rings", CATEB, "CC BY 2.0", "https://www.flickr.com/photos/69102917@N06/6938321813") },
  "oro-fino-24k": { src: "oro-fino-24k.jpg", alt: "Lámina de oro fino", caption: "Oro fino 24K: amarillo intenso, muy blando.", credit: cc("Fine gold", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Fine_gold.JPG") },
  "sello-18ct-anillo": { src: "sello-18ct-anillo.jpg", alt: "Sello 18ct dentro de un aro", caption: "Sello «18ct» grabado en la cara interna del aro.", credit: cc("Ring - Wedding, Gold, circa 1908", "David Paul / Museums Victoria", "CC BY 4.0", "https://collections.museumsvictoria.com.au/items/248048") },
  "marca-dentro-anillo": { src: "marca-dentro-anillo.jpg", alt: "Marca de fabricante dentro de un anillo de oro", caption: "Marca pequeña dentro del anillo: léala con lupa.", credit: cc("Posy ring (makers mark)", "Royal Institution of Cornwall, Anna Tyacke", "CC BY 2.0", "https://commons.wikimedia.org/w/index.php?curid=76673874") },
  "mosqueton": { src: "mosqueton.jpg", alt: "Cierres de mosquetón", caption: "Mosquetón: el sello suele ir en el cuerpo o en el gatillo; en cadenas, en la placa junto al cierre.", credit: cc("Lobster clasps", CATEB, "CC BY 2.0", "https://www.flickr.com/photos/69102917@N06/6709103745") },
  "limaduras-oro-750": { src: "limaduras-oro-750.jpg", alt: "Limaduras de oro 750", caption: "Limaduras de oro 750: el mismo metal en todo el corte.", credit: cc("750-gold filings", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:750-gold_filings.JPG") },
  "limaduras-oro-blanco": { src: "limaduras-oro-blanco.jpg", alt: "Limaduras de oro blanco", caption: "Limaduras de oro blanco: gris claro parejo.", credit: cc("White gold filings", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:White_gold_filings.JPG") },
  "oro-intacto-cobre-disuelto": { src: "oro-intacto-cobre-disuelto.jpg", alt: "Oro sin disolver y cobre disuelto en azul", caption: "El ácido nítrico no ataca el oro (láminas doradas) y disuelve el cobre (líquido azul-verde).", credit: cc("Gold and copper nitrate solution on a filter", "Francesco Sciara", "CC BY 4.0", "https://commons.wikimedia.org/w/index.php?curid=64596413") },
  "lupa-en-mano": { src: "lupa-en-mano.jpg", alt: "Lupa de joyero en la mano", caption: "Acerque la lupa al ojo y luego la pieza a la lupa.", credit: cc("A jeweller's loupe", "Billjones94", "CC BY-SA 4.0", "https://commons.wikimedia.org/w/index.php?curid=106174906") },
  "lijas-numeradas": { src: "lijas-numeradas.jpg", alt: "Lijas de distintos granos", caption: "El número es el grano: use 500 para la prueba inicial y hasta 1200 para marcas finas.", credit: cc("Sandpapers", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Sandpapers.JPG") },
  "usando-lija": { src: "usando-lija.jpg", alt: "Pieza de metal sobre lija", caption: "Frote una zona poco visible sobre la lija apoyada en superficie plana, con trazos cortos.", credit: cc("Making earrings - 5/14", CATEB, "CC BY 2.0", "https://www.flickr.com/photos/69102917@N06/8819509104") },
  "limas-joyero": { src: "limas-joyero.jpg", alt: "Limas de joyero", caption: "Limas de joyero: use una fina y una zona oculta.", credit: cc("Jewellery files", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Jewellery_files.jpg") },
  "usando-lima": { src: "usando-lima.jpg", alt: "Limando una pieza", caption: "Lime poco, en un borde oculto, hasta ver el metal interior.", credit: cc("Using files", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Using_files.JPG") },
  "acidos-joyero": { src: "acidos-joyero.jpg", alt: "Ácidos y pinza de joyero", caption: "Ácidos, recipiente y pinza: nunca toque la pieza ni el ácido con la mano.", credit: cc("Jewellery acids", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Jewellery_acids.jpg") },
  "balanza": { src: "balanza.jpg", alt: "Balanza electrónica de joyero", caption: "Balanza en cero antes de pesar; registre el peso bruto.", credit: cc("Electronic scales", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Electronic_scales.jpg") },
  "guantes-nitrilo": { src: "guantes-nitrilo.jpg", alt: "Guantes de nitrilo", caption: "Guantes de nitrilo durante toda la prueba con ácido.", credit: cc("Protective nitrile gloves", "Praewnaaaaaam", "CC BY-SA 4.0", "https://commons.wikimedia.org/w/index.php?curid=41019884") },
  "iman-atrae": { src: "iman-atrae.jpg", alt: "Imán de neodimio levantando una piedra", caption: "Así se ve cuando el imán atrae: la pieza se pega o se mueve. No es oro ni plata.", credit: cc("Magnetite sample with neodymium magnet", "GOKLuLe 盧樂", "CC BY-SA 3.0", "https://commons.wikimedia.org/w/index.php?curid=16946413") },
  "hierro-oxidado": { src: "hierro-oxidado.jpg", alt: "Aro de hierro oxidado", caption: "Hierro o acero: óxido rojizo y el imán lo atrae.", credit: cc("Steel Ring", "jasonbolonski", "CC BY 2.0", "https://www.flickr.com/photos/35619877@N05/4233046484") },
  "banado-desgastado": { src: "banado-desgastado.jpg", alt: "Pieza bañada en oro con el baño gastado", caption: "Baño de oro gastado: aparece otro metal verdoso o gris debajo.", credit: cc("Plated forgery of a gold half noble (FindID 283609)", "Portable Antiquities Scheme, Julian Watters", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Medieval_coin,_plated_forgery_of_a_gold_half_noble_of_Edward_III_(incomplete)_(FindID_283609).jpg") },
  "laton-banado": { src: "laton-banado.jpg", alt: "Anillos de latón bañados en oro", caption: "Latón bañado en oro: brilla como oro, pero la lima o el ácido revelan el latón.", credit: cc("Gold plated brass rings", "Euphy", "CC BY 2.0", "https://www.flickr.com/photos/15591303@N00/10161007493") },
  "laton-joyas": { src: "laton-joyas.jpg", alt: "Brazaletes de latón", caption: "Latón: amarillo opaco que se oscurece; con ácido se torna dorado o verde.", credit: cc("Brass Jewelry", "Paul Schadler", "CC BY 2.0", "https://www.flickr.com/photos/50602900@N02/5044947130") },
  "cobre-reaccion-verde": { src: "cobre-reaccion-verde.jpg", alt: "Cobre reaccionando con ácido nítrico", caption: "Cobre con ácido nítrico: color verde intenso. Es la reacción de una pieza que no es oro.", credit: cc("Взаимодействие солей меди (II) с концентрированной азотной кислотой", "Belkina N V", "CC0 1.0", "https://commons.wikimedia.org/w/index.php?curid=73049337") },
  "cobre-disuelto-azul": { src: "cobre-disuelto-azul.jpg", alt: "Solución azul de nitrato de cobre", caption: "El cobre disuelto en ácido deja el líquido azul-verde.", credit: cc("Copper(II) nitrate solution", "Philynator", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Copper(II)_nitrate_solution.jpg") },
  "plata-y-cobre": { src: "plata-y-cobre.jpg", alt: "Anillo de plata con cobre", caption: "Compare colores: plata (blanco) y cobre (rojizo).", credit: cc("Silver and copper ring", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Silver_and_copper_ring.jpg") },
  "metales-de-aleacion": { src: "metales-de-aleacion.jpg", alt: "Granallas de aleación", caption: "Metales de aleación (cobre, plata, etc.) que se mezclan con el oro y le dan su color y ley.", credit: cc("Master alloys", CATEB, "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Master_alloys.JPG") },
} satisfies Record<string, GuidePhoto>;
export type PhotoKey = keyof typeof PHOTOS;

export type Examples = { titulo: string; como?: PhotoKey[]; bueno?: PhotoKey[]; buenoTexto?: string; menor?: PhotoKey[]; menorTexto?: string; malo?: PhotoKey[]; maloTexto?: string; sellosMalos?: string[] };
export const EXAMPLES = {
  pesaje: { titulo: "Pesaje", como: ["balanza"], buenoTexto: "Balanza en cero, pieza limpia. Descuente piedras y partes no metálicas en «Deducciones»." },
  color: { titulo: "Color y desgaste", como: ["lupa-en-mano"], bueno: ["anillos-oro", "oro-blanco-750", "oro-fino-24k"], buenoTexto: "Color parejo en toda la pieza, también en bordes y zonas de roce.", malo: ["banado-desgastado", "laton-banado"], maloTexto: "En las zonas gastadas aparece otro color (gris, rojizo o verdoso): pieza bañada." },
  sello: { titulo: "Sello con lupa", como: ["lupa-en-mano", "lupa", "mosqueton"], bueno: ["sello-18ct-anillo", "marca-dentro-anillo", "sello-plata-925"], buenoTexto: "Sello nítido de ley (750, 18K, 585, 14K, 925). Aun así, confirme con las demás pruebas.", malo: [], maloTexto: "Sellos de piezas chapadas o de otro metal: no se compran como oro.", sellosMalos: ["GF", "GP", "HGE", "RGP", "1/20", "STEEL"] },
  iman: { titulo: "Imán", como: ["iman-neodimio"], buenoTexto: "La pieza no se mueve ni se pega al acercar el imán de neodimio.", malo: ["iman-atrae", "hierro-oxidado"], maloTexto: "La pieza se pega o se mueve hacia el imán: hierro, acero o níquel. No se compra." },
  piedra: { titulo: "Piedra o lija", como: ["piedra", "lija", "lijas-numeradas", "usando-lija"], bueno: ["piedra-toque", "piedra-toque-juego"], buenoTexto: "Marca del mismo color que la pieza, lista para el ácido.", malo: ["banado-desgastado"], maloTexto: "Al frotar desaparece el dorado y aparece otro metal: baño." },
  lima: { titulo: "Lima", como: ["limas-joyero", "usando-lima", "limas"], bueno: ["limaduras-oro-750", "limaduras-oro-blanco"], buenoTexto: "El corte y las limaduras son del mismo color que la superficie.", malo: ["laton-banado", "banado-desgastado"], maloTexto: "Debajo de la superficie aparece otro metal: bañado o enchapado." },
  acido: { titulo: "Ácido", como: ["acidos", "acidos-joyero", "guantes-nitrilo"], bueno: ["reaccion-18k", "reaccion-oro-blanco", "oro-intacto-cobre-disuelto"], buenoTexto: "Sin reacción: la marca sigue dorada. Oro 18K o más.", menor: ["reaccion-14k", "reaccion-14k-lamina", "reaccion-10k"], menorTexto: "Mancha café (14K) o café que burbujea (10K): es oro, pero de menor ley. Pague según la tabla.", malo: ["cobre-reaccion-verde", "cobre-disuelto-azul", "intensidad"], maloTexto: "Verde, efervescencia o líquido azul-verde: cobre o metal base. No se compra." },
  material: { titulo: "Material", bueno: ["anillos-oro", "sello-plata-925"], buenoTexto: "Oro o plata macizos, sin señales de baño.", malo: ["laton-joyas", "laton-banado", "hierro-oxidado", "banado-desgastado"], maloTexto: "Latón, acero, hierro o piezas bañadas: no se compran." },
} satisfies Record<string, Examples>;
export type ExampleKey = keyof typeof EXAMPLES;
