// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmmkrrlmvijvntnarfmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttbWtycmxtdmlqdm50bmFyZm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDYzNTIsImV4cCI6MjA2NTQ4MjM1Mn0.0Lj7RAlvwCh-xNpST8AEE_OHUNghqrljF5gkCfCvm4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);